import { challengeType, MatchData } from "./../../types/matchData";
export const MockMatchData1: MatchData = {
  metadata: {
    dataVersion: "2",
    matchId: "EUN1_3257741961",
    participants: [
      "PTNk4seF6xOMhqSLRkK76au6Z4tMoQeoXo2qT2IPsOfkuQLkDMtusJBPjrmgCS0TxTDXkryvnzBe3w",
      "26GbHHsyvlwxxaT4FSeJWIbpgmrqNN5ORDiv8XTc4jtCedYH0BcONbFGsOVR8GPNzR25v2ciitXmdQ",
      "JfK-z3f4Y5DpqliomR3UW-qS-qz7Q51CS33VWVGO9IQgK6nIOtVVNdiX8bNWcbrGkxP-o-9C7RUOiA",
      "cS5vwLjXVEioTNsbgfFHIolLXSM10ob6N3_qNod8x9UT0qCm4XrLgpefQ33Qexp4eroVz0hSOJmfAA",
      "Q10ko6N66lGtHBP0T3R1yvQk3QvXcfj-cFHtjy0pbp8k7JMzlXNhO0D-GHGMWo3BLuxpeJrCaH9krA",
      "falWk76tA_kEZZ4yBSKcQNmrb_hkW6Cw-tRZtPu0bbLlvLReflewV5EfdYgyYRIEyw2CBdu1Ju_E8g",
      "flqt87r0gFt0jkLEI9dlv2Srtto3gTJRkFPXWNYtbVDjbfJFyp2MtH6HoQdIPdyIO9Adu5hzf_DXEg",
      "l1tRZP9q6onsrK_tQGM5hQut5JzVlKxzkKQv66__F9UIVjvBgsVsi3eva6SCHmcIgMfLdg1WqteBYA",
      "KemdVt3dt9OdUcAJP8JFKS85mEmn_QLuF0WhvETnGdFGHfdWnCk92CiXL5umHw53-uQkNuKsTGKgXA",
      "eQHq45lNyjyGpjtqbRWAIB-39ftKYWvEaEqq-cOOSlM-sznts3_qzKdIxLAsWiMyKeErrMTskbUOLg",
    ],
  },
  info: {
    gameCreation: 1668714000385,
    gameDuration: 2226,
    gameEndTimestamp: 1668716335005,
    gameId: 3257741961,
    gameMode: "CLASSIC",
    gameName: "teambuilder-match-3257741961",
    gameStartTimestamp: 1668714108434,
    gameType: "MATCHED_GAME",
    gameVersion: "12.22.479.5277",
    mapId: 11,
    participants: [
      {
        allInPings: 6,
        assistMePings: 0,
        assists: 6,
        baitPings: 8,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 6,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 657,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 0,
          baronBuffGoldAdvantageOverThreshold: 1,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 0,
          buffsStolen: 1,
          completeSupportQuestInTime: 0,
          controlWardsPlaced: 0,
          damagePerMinute: 1518.4828659708003,
          damageTakenOnTeamPercentage: 0.1850766165499779,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 3,
          dodgeSkillShotsSmallWindow: 0,
          doubleAces: 0,
          dragonTakedowns: 3,
          earliestBaron: 2117.195747492342,
          earliestDragonTakedown: 1108.561544350936,
          earliestElderDragon: 1849.3645321002289,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 27,
          enemyJungleMonsterKills: 8,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          flawlessAces: 1,
          fullTeamTakedown: 0,
          gameLength: 2226.724221852379,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 542.4612310073837,
          hadOpenNexus: 0,
          highestChampionDamage: 1,
          immobilizeAndKillWithAlly: 3,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 5.666666666666667,
          killAfterHiddenWithAlly: 2,
          killParticipation: 0.5,
          killedChampTookFullTeamDamageSurvived: 0,
          killingSprees: 2,
          killsNearEnemyTurret: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 0,
          killsWithHelpFromEpicMonster: 0,
          knockEnemyIntoTeamAndKill: 3,
          landSkillShotsEarlyGame: 6,
          laneMinionsFirst10Minutes: 74,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 1,
          maxCsAdvantageOnLaneOpponent: 57.94999998807907,
          maxKillDeficit: 13,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 1,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6692,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 0,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 1,
          perfectGame: 0,
          pickKillWithAlly: 10,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 0,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 1,
          skillshotsDodged: 8,
          skillshotsHit: 50,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 5,
          soloTurretsLategame: 2,
          stealthWardsPlaced: 8,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 0,
          takedownOnFirstTurret: 0,
          takedowns: 17,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 3,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.3750456905148946,
          teamElderDragonKills: 1,
          teamRiftHeraldKills: 2,
          teleportTakedowns: 1,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 0,
          turretTakedowns: 7,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 14,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0.26488661766052246,
          visionScorePerMinute: 0.6078681636956117,
          wardTakedowns: 0,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 1,
        },
        champExperience: 23765,
        champLevel: 18,
        championId: 126,
        championName: "Jayce",
        championTransform: 0,
        commandPings: 4,
        consumablesPurchased: 3,
        damageDealtToBuildings: 16126,
        damageDealtToObjectives: 34770,
        damageDealtToTurrets: 16126,
        damageSelfMitigated: 26104,
        dangerPings: 0,
        deaths: 3,
        detectorWardsPlaced: 0,
        doubleKills: 1,
        dragonKills: 0,
        eligibleForProgression: true,
        enemyMissingPings: 0,
        enemyVisionPings: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 0,
        goldEarned: 20131,
        goldSpent: 17300,
        holdPings: 0,
        individualPosition: "TOP",
        inhibitorKills: 1,
        inhibitorTakedowns: 2,
        inhibitorsLost: 2,
        item0: 6692,
        item1: 6694,
        item2: 3042,
        item3: 3814,
        item4: 3158,
        item5: 3156,
        item6: 3363,
        itemsPurchased: 28,
        killingSprees: 2,
        kills: 11,
        lane: "MIDDLE",
        largestCriticalStrike: 0,
        largestKillingSpree: 6,
        largestMultiKill: 2,
        longestTimeSpentLiving: 637,
        magicDamageDealt: 35248,
        magicDamageDealtToChampions: 10994,
        magicDamageTaken: 12190,
        needVisionPings: 0,
        neutralMinionsKilled: 12,
        nexusKills: 0,
        nexusLost: 0,
        nexusTakedowns: 1,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 0,
        participantId: 1,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5002,
            flex: 5008,
            offense: 5008,
          },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                {
                  perk: 8369,
                  var1: 2159,
                  var2: 1857,
                  var3: 0,
                },
                {
                  perk: 8304,
                  var1: 11,
                  var2: 1,
                  var3: 5,
                },
                {
                  perk: 8345,
                  var1: 3,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8347,
                  var1: 0,
                  var2: 0,
                  var3: 0,
                },
              ],
              style: 8300,
            },
            {
              description: "subStyle",
              selections: [
                {
                  perk: 8236,
                  var1: 28,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8226,
                  var1: 250,
                  var2: 2102,
                  var3: 0,
                },
              ],
              style: 8200,
            },
          ],
        },
        physicalDamageDealt: 307365,
        physicalDamageDealtToChampions: 43535,
        physicalDamageTaken: 13214,
        profileIcon: 4096,
        pushPings: 0,
        puuid:
          "PTNk4seF6xOMhqSLRkK76au6Z4tMoQeoXo2qT2IPsOfkuQLkDMtusJBPjrmgCS0TxTDXkryvnzBe3w",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "DUO",
        sightWardsBoughtInGame: 0,
        spell1Casts: 199,
        spell2Casts: 118,
        spell3Casts: 161,
        spell4Casts: 179,
        summoner1Casts: 3,
        summoner1Id: 12,
        summoner2Casts: 3,
        summoner2Id: 4,
        summonerId: "sbJVWwNw6uzR8lC4FIGRBqR51e5k7WjqCRVY4oU6fx-kZ5U",
        summonerLevel: 307,
        summonerName: "Saagrai",
        teamEarlySurrendered: false,
        teamId: 100,
        teamPosition: "TOP",
        timeCCingOthers: 20,
        timePlayed: 2226,
        totalDamageDealt: 346452,
        totalDamageDealtToChampions: 56354,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 26430,
        totalHeal: 10565,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 299,
        totalTimeCCDealt: 235,
        totalTimeSpentDead: 113,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 3838,
        trueDamageDealtToChampions: 1823,
        trueDamageTaken: 1024,
        turretKills: 6,
        turretTakedowns: 7,
        turretsLost: 8,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 22,
        visionWardsBoughtInGame: 0,
        wardsKilled: 0,
        wardsPlaced: 15,
        win: true,
      },
      {
        allInPings: 1,
        assistMePings: 4,
        assists: 7,
        baitPings: 1,
        baronKills: 1,
        basicPings: 0,
        bountyLevel: 1,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 162,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 107.90000015497208,
          baronBuffGoldAdvantageOverThreshold: 1,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 850,
          buffsStolen: 2,
          completeSupportQuestInTime: 0,
          controlWardsPlaced: 0,
          damagePerMinute: 762.5656125929863,
          damageTakenOnTeamPercentage: 0.2663702867990691,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 10,
          dodgeSkillShotsSmallWindow: 3,
          doubleAces: 0,
          dragonTakedowns: 4,
          earliestBaron: 2117.195747492342,
          earliestDragonTakedown: 371.63342041297955,
          earliestElderDragon: 1849.3645321002289,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 0,
          enemyJungleMonsterKills: 8,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          flawlessAces: 1,
          fullTeamTakedown: 0,
          gameLength: 2226.724221852379,
          goldPerMinute: 467.7673404571931,
          hadOpenNexus: 0,
          immobilizeAndKillWithAlly: 0,
          initialBuffCount: 2,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 48.000000059604645,
          junglerKillsEarlyJungle: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 1.6,
          killAfterHiddenWithAlly: 2,
          killParticipation: 0.47058823529411764,
          killedChampTookFullTeamDamageSurvived: 0,
          killsNearEnemyTurret: 1,
          killsOnLanersEarlyJungleAsJungler: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 0,
          killsWithHelpFromEpicMonster: 0,
          knockEnemyIntoTeamAndKill: 0,
          landSkillShotsEarlyGame: 0,
          laneMinionsFirst10Minutes: 1,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 1,
          maxCsAdvantageOnLaneOpponent: 4.000000029802322,
          maxKillDeficit: 13,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: -55.1000000834465,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 1,
          multikillsAfterAggressiveFlash: 1,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 2,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 1,
          perfectGame: 0,
          pickKillWithAlly: 11,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 2,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 2,
          skillshotsDodged: 21,
          skillshotsHit: 0,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 1,
          stealthWardsPlaced: 1,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 0,
          takedownOnFirstTurret: 0,
          takedowns: 16,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 2,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 1,
          teamBaronKills: 1,
          teamDamagePercentage: 0.1883438747627922,
          teamElderDragonKills: 1,
          teamRiftHeraldKills: 2,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 2,
          turretTakedowns: 1,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 1,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: -0.25372183322906494,
          visionScorePerMinute: 0.696319027486604,
          wardTakedowns: 8,
          wardTakedownsBefore20M: 3,
          wardsGuarded: 1,
        } as challengeType,
        champExperience: 16714,
        champLevel: 17,
        championId: 11,
        championName: "MasterYi",
        championTransform: 0,
        commandPings: 9,
        consumablesPurchased: 1,
        damageDealtToBuildings: 748,
        damageDealtToObjectives: 45588,
        damageDealtToTurrets: 748,
        damageSelfMitigated: 27871,
        dangerPings: 0,
        deaths: 10,
        detectorWardsPlaced: 0,
        doubleKills: 1,
        dragonKills: 4,
        eligibleForProgression: true,
        enemyMissingPings: 5,
        enemyVisionPings: 4,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 1,
        goldEarned: 17359,
        goldSpent: 15200,
        holdPings: 0,
        individualPosition: "JUNGLE",
        inhibitorKills: 1,
        inhibitorTakedowns: 1,
        inhibitorsLost: 2,
        item0: 3091,
        item1: 3111,
        item2: 3153,
        item3: 3124,
        item4: 6333,
        item5: 6670,
        item6: 3364,
        itemsPurchased: 27,
        killingSprees: 2,
        kills: 9,
        lane: "JUNGLE",
        largestCriticalStrike: 0,
        largestKillingSpree: 2,
        largestMultiKill: 2,
        longestTimeSpentLiving: 465,
        magicDamageDealt: 15681,
        magicDamageDealtToChampions: 2231,
        magicDamageTaken: 16202,
        needVisionPings: 0,
        neutralMinionsKilled: 152,
        nexusKills: 0,
        nexusLost: 0,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 5,
        participantId: 2,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5002,
            flex: 5008,
            offense: 5005,
          },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                {
                  perk: 8008,
                  var1: 22,
                  var2: 1,
                  var3: 0,
                },
                {
                  perk: 9111,
                  var1: 789,
                  var2: 320,
                  var3: 0,
                },
                {
                  perk: 9104,
                  var1: 17,
                  var2: 20,
                  var3: 0,
                },
                {
                  perk: 8014,
                  var1: 748,
                  var2: 0,
                  var3: 0,
                },
              ],
              style: 8000,
            },
            {
              description: "subStyle",
              selections: [
                {
                  perk: 8138,
                  var1: 18,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8135,
                  var1: 550,
                  var2: 5,
                  var3: 0,
                },
              ],
              style: 8100,
            },
          ],
        },
        physicalDamageDealt: 169872,
        physicalDamageDealtToChampions: 18900,
        physicalDamageTaken: 17903,
        profileIcon: 8,
        pushPings: 1,
        puuid:
          "26GbHHsyvlwxxaT4FSeJWIbpgmrqNN5ORDiv8XTc4jtCedYH0BcONbFGsOVR8GPNzR25v2ciitXmdQ",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "NONE",
        sightWardsBoughtInGame: 0,
        spell1Casts: 77,
        spell2Casts: 13,
        spell3Casts: 58,
        spell4Casts: 14,
        summoner1Casts: 5,
        summoner1Id: 4,
        summoner2Casts: 19,
        summoner2Id: 11,
        summonerId: "jkPQ0EctBKq0Bb_1BxdOMCOtoJ8E4gLcRUl8I49ewwxa2do",
        summonerLevel: 317,
        summonerName: "F1NG3R0FAw3sOMe",
        teamEarlySurrendered: false,
        teamId: 100,
        teamPosition: "JUNGLE",
        timeCCingOthers: 10,
        timePlayed: 2226,
        totalDamageDealt: 250556,
        totalDamageDealtToChampions: 28300,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 38039,
        totalHeal: 3862,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 47,
        totalTimeCCDealt: 283,
        totalTimeSpentDead: 361,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 65001,
        trueDamageDealtToChampions: 7168,
        trueDamageTaken: 3933,
        turretKills: 1,
        turretTakedowns: 1,
        turretsLost: 8,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 25,
        visionWardsBoughtInGame: 0,
        wardsKilled: 8,
        wardsPlaced: 1,
        win: true,
      },
      {
        allInPings: 0,
        assistMePings: 0,
        assists: 6,
        baitPings: 0,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 4,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 409,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 17.000000029802322,
          baronBuffGoldAdvantageOverThreshold: 1,
          baronTakedowns: 0,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 600,
          buffsStolen: 0,
          completeSupportQuestInTime: 0,
          controlWardTimeCoverageInRiverOrEnemyHalf: 0.05710880331186569,
          controlWardsPlaced: 3,
          damagePerMinute: 649.0263329725481,
          damageTakenOnTeamPercentage: 0.22206645756284613,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 3,
          dodgeSkillShotsSmallWindow: 0,
          doubleAces: 0,
          dragonTakedowns: 2,
          earliestBaron: 2117.195747492342,
          earliestDragonTakedown: 371.63342041297955,
          earliestElderDragon: 1849.3645321002289,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 48,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          flawlessAces: 1,
          fullTeamTakedown: 0,
          gameLength: 2226.724221852379,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 410.94752008121134,
          hadOpenNexus: 0,
          highestCrowdControlScore: 1,
          immobilizeAndKillWithAlly: 6,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 3.3333333333333335,
          killAfterHiddenWithAlly: 2,
          killParticipation: 0.29411764705882354,
          killedChampTookFullTeamDamageSurvived: 0,
          killingSprees: 1,
          killsNearEnemyTurret: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 0,
          killsWithHelpFromEpicMonster: 0,
          knockEnemyIntoTeamAndKill: 0,
          landSkillShotsEarlyGame: 3,
          laneMinionsFirst10Minutes: 62,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 1,
          maxCsAdvantageOnLaneOpponent: 7.749999970197678,
          maxKillDeficit: 13,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 1,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6657,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 0,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 1,
          perfectGame: 0,
          pickKillWithAlly: 8,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 0,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 0,
          shortestTimeToAceFromFirstTakedown: 41.22065832820772,
          skillshotsDodged: 6,
          skillshotsHit: 23,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 8,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 5,
          takedownOnFirstTurret: 0,
          takedowns: 10,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 0,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.16030113652709466,
          teamElderDragonKills: 1,
          teamRiftHeraldKills: 2,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 1,
          turretTakedowns: 2,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 12,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: -0.028397202491760254,
          visionScorePerMinute: 0.6485712106018071,
          wardTakedowns: 1,
          wardTakedownsBefore20M: 1,
          wardsGuarded: 0,
        } as challengeType,
        champExperience: 22864,
        champLevel: 18,
        championId: 34,
        championName: "Anivia",
        championTransform: 0,
        commandPings: 8,
        consumablesPurchased: 5,
        damageDealtToBuildings: 1516,
        damageDealtToObjectives: 8895,
        damageDealtToTurrets: 1516,
        damageSelfMitigated: 18377,
        dangerPings: 0,
        deaths: 3,
        detectorWardsPlaced: 3,
        doubleKills: 1,
        dragonKills: 0,
        eligibleForProgression: true,
        enemyMissingPings: 11,
        enemyVisionPings: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 0,
        goldEarned: 15251,
        goldSpent: 14125,
        holdPings: 0,
        individualPosition: "MIDDLE",
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 2,
        item0: 6657,
        item1: 2033,
        item2: 3157,
        item3: 3040,
        item4: 3020,
        item5: 4645,
        item6: 3363,
        itemsPurchased: 22,
        killingSprees: 1,
        kills: 4,
        lane: "MIDDLE",
        largestCriticalStrike: 0,
        largestKillingSpree: 4,
        largestMultiKill: 2,
        longestTimeSpentLiving: 825,
        magicDamageDealt: 218869,
        magicDamageDealtToChampions: 21270,
        magicDamageTaken: 19159,
        needVisionPings: 0,
        neutralMinionsKilled: 19,
        nexusKills: 0,
        nexusLost: 0,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 0,
        participantId: 3,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5003,
            flex: 5008,
            offense: 5008,
          },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                {
                  perk: 8112,
                  var1: 1736,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8126,
                  var1: 1253,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8138,
                  var1: 30,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8105,
                  var1: 11,
                  var2: 4,
                  var3: 0,
                },
              ],
              style: 8100,
            },
            {
              description: "subStyle",
              selections: [
                {
                  perk: 8009,
                  var1: 4532,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8014,
                  var1: 415,
                  var2: 0,
                  var3: 0,
                },
              ],
              style: 8000,
            },
          ],
        },
        physicalDamageDealt: 15939,
        physicalDamageDealtToChampions: 1378,
        physicalDamageTaken: 11625,
        profileIcon: 29,
        pushPings: 0,
        puuid:
          "JfK-z3f4Y5DpqliomR3UW-qS-qz7Q51CS33VWVGO9IQgK6nIOtVVNdiX8bNWcbrGkxP-o-9C7RUOiA",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "DUO",
        sightWardsBoughtInGame: 0,
        spell1Casts: 117,
        spell2Casts: 30,
        spell3Casts: 117,
        spell4Casts: 145,
        summoner1Casts: 5,
        summoner1Id: 12,
        summoner2Casts: 4,
        summoner2Id: 4,
        summonerId: "3DioTpu_AeN-jZbKInGnxYtC-LiSXMY6s5hpgLfeQmy9jow",
        summonerLevel: 347,
        summonerName: "Bounsweed",
        teamEarlySurrendered: false,
        teamId: 100,
        teamPosition: "MIDDLE",
        timeCCingOthers: 45,
        timePlayed: 2226,
        totalDamageDealt: 250125,
        totalDamageDealtToChampions: 24086,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 31712,
        totalHeal: 6769,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 268,
        totalTimeCCDealt: 1468,
        totalTimeSpentDead: 106,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 15315,
        trueDamageDealtToChampions: 1437,
        trueDamageTaken: 927,
        turretKills: 1,
        turretTakedowns: 2,
        turretsLost: 8,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 24,
        visionWardsBoughtInGame: 3,
        wardsKilled: 1,
        wardsPlaced: 15,
        win: true,
      },
      {
        allInPings: 0,
        assistMePings: 0,
        assists: 8,
        baitPings: 0,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 2,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 171,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 20.400000035762787,
          baronBuffGoldAdvantageOverThreshold: 1,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 375,
          buffsStolen: 0,
          completeSupportQuestInTime: 0,
          controlWardsPlaced: 1,
          damagePerMinute: 977.345959826397,
          damageTakenOnTeamPercentage: 0.1993132909340478,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 12,
          dodgeSkillShotsSmallWindow: 4,
          doubleAces: 0,
          dragonTakedowns: 2,
          earliestBaron: 2117.195747492342,
          earliestDragonTakedown: 779.095497809957,
          earliestElderDragon: 1849.3645321002289,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 7,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          flawlessAces: 1,
          fullTeamTakedown: 0,
          gameLength: 2226.724221852379,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 428.6529182960396,
          hadOpenNexus: 0,
          immobilizeAndKillWithAlly: 5,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0.4000000059604645,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 1.5,
          killAfterHiddenWithAlly: 1,
          killParticipation: 0.5294117647058824,
          killedChampTookFullTeamDamageSurvived: 0,
          killsNearEnemyTurret: 2,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 0,
          killsWithHelpFromEpicMonster: 1,
          knockEnemyIntoTeamAndKill: 5,
          landSkillShotsEarlyGame: 0,
          laneMinionsFirst10Minutes: 40,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 1,
          maxCsAdvantageOnLaneOpponent: 29.900000035762787,
          maxKillDeficit: 13,
          maxLevelLeadLaneOpponent: 2,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 1,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6672,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 0,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 1,
          perfectGame: 0,
          pickKillWithAlly: 14,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 0,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 1,
          shortestTimeToAceFromFirstTakedown: 41.22065832820772,
          skillshotsDodged: 26,
          skillshotsHit: 0,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 1,
          stealthWardsPlaced: 7,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 0,
          takedownOnFirstTurret: 0,
          takedowns: 18,
          takedownsAfterGainingLevelAdvantage: 1,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 4,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.24139185142579153,
          teamElderDragonKills: 1,
          teamRiftHeraldKills: 2,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 0,
          turretTakedowns: 3,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 8,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: -0.39037036895751953,
          visionScorePerMinute: 0.48189221913053487,
          wardTakedowns: 0,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 1,
        } as challengeType,
        champExperience: 16652,
        champLevel: 17,
        championId: 18,
        championName: "Tristana",
        championTransform: 0,
        commandPings: 0,
        consumablesPurchased: 4,
        damageDealtToBuildings: 4802,
        damageDealtToObjectives: 29456,
        damageDealtToTurrets: 4802,
        damageSelfMitigated: 13939,
        dangerPings: 0,
        deaths: 12,
        detectorWardsPlaced: 1,
        doubleKills: 1,
        dragonKills: 1,
        eligibleForProgression: true,
        enemyMissingPings: 1,
        enemyVisionPings: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 0,
        goldEarned: 15908,
        goldSpent: 13425,
        holdPings: 0,
        individualPosition: "BOTTOM",
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 2,
        item0: 6672,
        item1: 1038,
        item2: 3006,
        item3: 1053,
        item4: 3031,
        item5: 3046,
        item6: 3363,
        itemsPurchased: 26,
        killingSprees: 3,
        kills: 10,
        lane: "BOTTOM",
        largestCriticalStrike: 901,
        largestKillingSpree: 2,
        largestMultiKill: 2,
        longestTimeSpentLiving: 285,
        magicDamageDealt: 27260,
        magicDamageDealtToChampions: 3177,
        magicDamageTaken: 9422,
        needVisionPings: 0,
        neutralMinionsKilled: 28,
        nexusKills: 1,
        nexusLost: 0,
        nexusTakedowns: 1,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 0,
        participantId: 4,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5002,
            flex: 5008,
            offense: 5005,
          },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                {
                  perk: 9923,
                  var1: 79,
                  var2: 87,
                  var3: 0,
                },
                {
                  perk: 8139,
                  var1: 983,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8138,
                  var1: 18,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8135,
                  var1: 550,
                  var2: 5,
                  var3: 0,
                },
              ],
              style: 8100,
            },
            {
              description: "subStyle",
              selections: [
                {
                  perk: 9111,
                  var1: 730,
                  var2: 360,
                  var3: 0,
                },
                {
                  perk: 9103,
                  var1: 22,
                  var2: 50,
                  var3: 0,
                },
              ],
              style: 8000,
            },
          ],
        },
        physicalDamageDealt: 178541,
        physicalDamageDealtToChampions: 27331,
        physicalDamageTaken: 18423,
        profileIcon: 5547,
        pushPings: 0,
        puuid:
          "cS5vwLjXVEioTNsbgfFHIolLXSM10ob6N3_qNod8x9UT0qCm4XrLgpefQ33Qexp4eroVz0hSOJmfAA",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "CARRY",
        sightWardsBoughtInGame: 0,
        spell1Casts: 67,
        spell2Casts: 42,
        spell3Casts: 55,
        spell4Casts: 7,
        summoner1Casts: 6,
        summoner1Id: 4,
        summoner2Casts: 9,
        summoner2Id: 3,
        summonerId: "_T6vGcIQZfodXyMuwBOb4XPT29fozilVPOjwqlr9pZuC1BM",
        summonerLevel: 352,
        summonerName: "Kawaii Girl",
        teamEarlySurrendered: false,
        teamId: 100,
        teamPosition: "BOTTOM",
        timeCCingOthers: 14,
        timePlayed: 2226,
        totalDamageDealt: 229364,
        totalDamageDealtToChampions: 36271,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 28463,
        totalHeal: 3390,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 180,
        totalTimeCCDealt: 116,
        totalTimeSpentDead: 308,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 23561,
        trueDamageDealtToChampions: 5762,
        trueDamageTaken: 617,
        turretKills: 1,
        turretTakedowns: 3,
        turretsLost: 8,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 17,
        visionWardsBoughtInGame: 3,
        wardsKilled: 0,
        wardsPlaced: 13,
        win: true,
      },
      {
        allInPings: 0,
        assistMePings: 0,
        assists: 20,
        baitPings: 0,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 0,
        challenges: {
          "12AssistStreakCount": 1,
          abilityUses: 275,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 0,
          baronBuffGoldAdvantageOverThreshold: 1,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 0,
          buffsStolen: 0,
          completeSupportQuestInTime: 0,
          controlWardTimeCoverageInRiverOrEnemyHalf: 0.07744572914613283,
          controlWardsPlaced: 8,
          damagePerMinute: 141.37356056546042,
          damageTakenOnTeamPercentage: 0.1271733481540591,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 7,
          dodgeSkillShotsSmallWindow: 3,
          doubleAces: 0,
          dragonTakedowns: 4,
          earliestBaron: 2117.195747492342,
          earliestDragonTakedown: 779.095497809957,
          earliestElderDragon: 1849.3645321002289,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 8589.498046875,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 24,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          flawlessAces: 1,
          fullTeamTakedown: 0,
          gameLength: 2226.724221852379,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 247.49470793426144,
          hadOpenNexus: 0,
          immobilizeAndKillWithAlly: 3,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 2.857142857142857,
          killAfterHiddenWithAlly: 4,
          killParticipation: 0.5882352941176471,
          killedChampTookFullTeamDamageSurvived: 0,
          killsNearEnemyTurret: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 0,
          killsWithHelpFromEpicMonster: 0,
          knockEnemyIntoTeamAndKill: 1,
          landSkillShotsEarlyGame: 14,
          laneMinionsFirst10Minutes: 1,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 1,
          maxCsAdvantageOnLaneOpponent: 0,
          maxKillDeficit: 13,
          maxLevelLeadLaneOpponent: 3,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 2065,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 0,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 1,
          perfectGame: 0,
          pickKillWithAlly: 16,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 0,
          saveAllyFromDeath: 1,
          scuttleCrabKills: 0,
          shortestTimeToAceFromFirstTakedown: 41.22065832820772,
          skillshotsDodged: 19,
          skillshotsHit: 52,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 38,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 2,
          takedownOnFirstTurret: 0,
          takedowns: 20,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 2,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.034917446769427006,
          teamElderDragonKills: 1,
          teamRiftHeraldKills: 2,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 0,
          turretTakedowns: 3,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 0,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0.1060715913772583,
          visionScorePerMinute: 2.310978939493868,
          wardTakedowns: 7,
          wardTakedownsBefore20M: 3,
          wardsGuarded: 0,
        } as challengeType,
        champExperience: 14946,
        champLevel: 16,
        championId: 40,
        championName: "Janna",
        championTransform: 0,
        commandPings: 0,
        consumablesPurchased: 9,
        damageDealtToBuildings: 686,
        damageDealtToObjectives: 3130,
        damageDealtToTurrets: 686,
        damageSelfMitigated: 7835,
        dangerPings: 0,
        deaths: 7,
        detectorWardsPlaced: 8,
        doubleKills: 0,
        dragonKills: 0,
        eligibleForProgression: true,
        enemyMissingPings: 0,
        enemyVisionPings: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 0,
        goldEarned: 9185,
        goldSpent: 7625,
        holdPings: 0,
        individualPosition: "UTILITY",
        inhibitorKills: 0,
        inhibitorTakedowns: 2,
        inhibitorsLost: 2,
        item0: 2065,
        item1: 3853,
        item2: 3504,
        item3: 2055,
        item4: 3916,
        item5: 3158,
        item6: 3364,
        itemsPurchased: 25,
        killingSprees: 0,
        kills: 0,
        lane: "BOTTOM",
        largestCriticalStrike: 0,
        largestKillingSpree: 0,
        largestMultiKill: 0,
        longestTimeSpentLiving: 500,
        magicDamageDealt: 14932,
        magicDamageDealtToChampions: 3996,
        magicDamageTaken: 9477,
        needVisionPings: 0,
        neutralMinionsKilled: 0,
        nexusKills: 0,
        nexusLost: 0,
        nexusTakedowns: 1,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 0,
        participantId: 5,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5002,
            flex: 5008,
            offense: 5008,
          },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                {
                  perk: 8214,
                  var1: 620,
                  var2: 2025,
                  var3: 0,
                },
                {
                  perk: 8226,
                  var1: 250,
                  var2: 382,
                  var3: 0,
                },
                {
                  perk: 8210,
                  var1: 10,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8237,
                  var1: 458,
                  var2: 0,
                  var3: 0,
                },
              ],
              style: 8200,
            },
            {
              description: "subStyle",
              selections: [
                {
                  perk: 8345,
                  var1: 3,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8347,
                  var1: 0,
                  var2: 0,
                  var3: 0,
                },
              ],
              style: 8300,
            },
          ],
        },
        physicalDamageDealt: 3715,
        physicalDamageDealtToChampions: 825,
        physicalDamageTaken: 8088,
        profileIcon: 5574,
        pushPings: 0,
        puuid:
          "Q10ko6N66lGtHBP0T3R1yvQk3QvXcfj-cFHtjy0pbp8k7JMzlXNhO0D-GHGMWo3BLuxpeJrCaH9krA",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "SUPPORT",
        sightWardsBoughtInGame: 0,
        spell1Casts: 163,
        spell2Casts: 25,
        spell3Casts: 81,
        spell4Casts: 6,
        summoner1Casts: 4,
        summoner1Id: 14,
        summoner2Casts: 4,
        summoner2Id: 4,
        summonerId: "i8pjEGyIQnaweeF-qdEvPN2wKbr3U5KSxe3z4wr-_Cq7LGU",
        summonerLevel: 431,
        summonerName: "vilukun",
        teamEarlySurrendered: false,
        teamId: 100,
        teamPosition: "UTILITY",
        timeCCingOthers: 24,
        timePlayed: 2226,
        totalDamageDealt: 20602,
        totalDamageDealtToChampions: 5246,
        totalDamageShieldedOnTeammates: 5904,
        totalDamageTaken: 18161,
        totalHeal: 6751,
        totalHealsOnTeammates: 2684,
        totalMinionsKilled: 13,
        totalTimeCCDealt: 116,
        totalTimeSpentDead: 135,
        totalUnitsHealed: 12,
        tripleKills: 0,
        trueDamageDealt: 1954,
        trueDamageDealtToChampions: 424,
        trueDamageTaken: 595,
        turretKills: 0,
        turretTakedowns: 3,
        turretsLost: 8,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 85,
        visionWardsBoughtInGame: 9,
        wardsKilled: 6,
        wardsPlaced: 46,
        win: true,
      },
      {
        allInPings: 5,
        assistMePings: 2,
        assists: 6,
        baitPings: 1,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 0,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 242,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 0,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 0,
          buffsStolen: 0,
          completeSupportQuestInTime: 0,
          controlWardsPlaced: 0,
          damagePerMinute: 513.0726813745688,
          damageTakenOnTeamPercentage: 0.3214518506024157,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 6,
          dodgeSkillShotsSmallWindow: 1,
          doubleAces: 0,
          dragonTakedowns: 0,
          earliestBaron: 1600.827670495282,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 36,
          enemyJungleMonsterKills: 4.800000011920929,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          firstTurretKilledTime: 957.7183454968596,
          flawlessAces: 0,
          fullTeamTakedown: 0,
          gameLength: 2226.724221852379,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 372.3794266596302,
          hadOpenNexus: 0,
          immobilizeAndKillWithAlly: 3,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 1.3333333333333333,
          killAfterHiddenWithAlly: 0,
          killParticipation: 0.22857142857142856,
          killedChampTookFullTeamDamageSurvived: 0,
          killsNearEnemyTurret: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 1,
          killsWithHelpFromEpicMonster: 0,
          knockEnemyIntoTeamAndKill: 0,
          landSkillShotsEarlyGame: 0,
          laneMinionsFirst10Minutes: 67,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 8,
          maxKillDeficit: 0,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 3084,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 1,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          pickKillWithAlly: 6,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 0,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 0,
          skillshotsDodged: 9,
          skillshotsHit: 18,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 1,
          soloTurretsLategame: 2,
          stealthWardsPlaced: 10,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 4,
          takedownOnFirstTurret: 0,
          takedowns: 8,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 2,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.17949765529300685,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 2,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 3,
          turretTakedowns: 3,
          turretsTakenWithRiftHerald: 5,
          twentyMinionsIn3SecondsCount: 12,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: -0.2094152569770813,
          visionScorePerMinute: 0.4805712830016837,
          wardTakedowns: 1,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 1,
        } as any,
        champExperience: 19849,
        champLevel: 18,
        championId: 14,
        championName: "Sion",
        championTransform: 0,
        commandPings: 0,
        consumablesPurchased: 1,
        damageDealtToBuildings: 8012,
        damageDealtToObjectives: 10846,
        damageDealtToTurrets: 8012,
        damageSelfMitigated: 98319,
        dangerPings: 0,
        deaths: 6,
        detectorWardsPlaced: 0,
        doubleKills: 0,
        dragonKills: 0,
        eligibleForProgression: true,
        enemyMissingPings: 3,
        enemyVisionPings: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 4,
        goldEarned: 13819,
        goldSpent: 13700,
        holdPings: 1,
        individualPosition: "TOP",
        inhibitorKills: 1,
        inhibitorTakedowns: 1,
        inhibitorsLost: 2,
        item0: 3047,
        item1: 3084,
        item2: 3068,
        item3: 3181,
        item4: 3110,
        item5: 1011,
        item6: 3340,
        itemsPurchased: 22,
        killingSprees: 0,
        kills: 2,
        lane: "TOP",
        largestCriticalStrike: 0,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        longestTimeSpentLiving: 830,
        magicDamageDealt: 76682,
        magicDamageDealtToChampions: 6723,
        magicDamageTaken: 18394,
        needVisionPings: 0,
        neutralMinionsKilled: 5,
        nexusKills: 0,
        nexusLost: 1,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 19,
        participantId: 6,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5003,
            flex: 5003,
            offense: 5008,
          },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                {
                  perk: 8437,
                  var1: 1558,
                  var2: 1212,
                  var3: 0,
                },
                {
                  perk: 8446,
                  var1: 4832,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8444,
                  var1: 3062,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8242,
                  var1: 118,
                  var2: 0,
                  var3: 0,
                },
              ],
              style: 8400,
            },
            {
              description: "subStyle",
              selections: [
                {
                  perk: 8304,
                  var1: 10,
                  var2: 3,
                  var3: 0,
                },
                {
                  perk: 8316,
                  var1: 2960,
                  var2: 0,
                  var3: 0,
                },
              ],
              style: 8300,
            },
          ],
        },
        physicalDamageDealt: 134108,
        physicalDamageDealtToChampions: 11985,
        physicalDamageTaken: 36410,
        profileIcon: 4783,
        pushPings: 0,
        puuid:
          "falWk76tA_kEZZ4yBSKcQNmrb_hkW6Cw-tRZtPu0bbLlvLReflewV5EfdYgyYRIEyw2CBdu1Ju_E8g",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "SOLO",
        sightWardsBoughtInGame: 0,
        spell1Casts: 85,
        spell2Casts: 88,
        spell3Casts: 58,
        spell4Casts: 11,
        summoner1Casts: 5,
        summoner1Id: 4,
        summoner2Casts: 6,
        summoner2Id: 12,
        summonerId: "-b3r0xegyKvX2rQEGHC_jzwElmdSFJGxSpMrnPZLnwT9XR0",
        summonerLevel: 256,
        summonerName: "nezlomenanoha",
        teamEarlySurrendered: false,
        teamId: 200,
        teamPosition: "TOP",
        timeCCingOthers: 35,
        timePlayed: 2226,
        totalDamageDealt: 222501,
        totalDamageDealtToChampions: 19041,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 61579,
        totalHeal: 1598,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 258,
        totalTimeCCDealt: 1229,
        totalTimeSpentDead: 230,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 11709,
        trueDamageDealtToChampions: 332,
        trueDamageTaken: 6775,
        turretKills: 2,
        turretTakedowns: 3,
        turretsLost: 9,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 17,
        visionWardsBoughtInGame: 0,
        wardsKilled: 1,
        wardsPlaced: 10,
        win: false,
      },
      {
        allInPings: 1,
        assistMePings: 1,
        assists: 12,
        baitPings: 1,
        baronKills: 1,
        basicPings: 0,
        bountyLevel: 0,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 1206,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 132.5000002682209,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 1,
          bountyGold: 0,
          buffsStolen: 1,
          completeSupportQuestInTime: 0,
          controlWardTimeCoverageInRiverOrEnemyHalf: 0.25331270215389684,
          controlWardsPlaced: 1,
          damagePerMinute: 953.8864006060172,
          damageTakenOnTeamPercentage: 0.2268892626231455,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 5,
          dodgeSkillShotsSmallWindow: 0,
          doubleAces: 0,
          dragonTakedowns: 0,
          earliestBaron: 1600.827670495282,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 6605.04541015625,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 2,
          enemyJungleMonsterKills: 23.400000035762787,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          fastestLegendary: 1217.648673543323,
          firstTurretKilledTime: 957.7183454968596,
          flawlessAces: 0,
          fullTeamTakedown: 0,
          gameLength: 2226.724221852379,
          goldPerMinute: 475.4652023912321,
          hadOpenNexus: 0,
          immobilizeAndKillWithAlly: 0,
          initialBuffCount: 2,
          initialCrabCount: 2,
          jungleCsBefore10Minutes: 71.6000000834465,
          junglerKillsEarlyJungle: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 4.4,
          killAfterHiddenWithAlly: 2,
          killParticipation: 0.6285714285714286,
          killedChampTookFullTeamDamageSurvived: 0,
          killingSprees: 1,
          killsNearEnemyTurret: 1,
          killsOnLanersEarlyJungleAsJungler: 1,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 1,
          killsWithHelpFromEpicMonster: 0,
          knockEnemyIntoTeamAndKill: 0,
          landSkillShotsEarlyGame: 1,
          laneMinionsFirst10Minutes: 0,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 1,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 70.50000014901161,
          maxKillDeficit: 0,
          maxLevelLeadLaneOpponent: 2,
          moreEnemyJungleThanOpponent: -32.40000003576279,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 1,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 4636,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 2,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          pickKillWithAlly: 13,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 2,
          saveAllyFromDeath: 1,
          scuttleCrabKills: 5,
          skillshotsDodged: 4,
          skillshotsHit: 27,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 4,
          soloTurretsLategame: 1,
          stealthWardsPlaced: 2,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 0,
          takedownOnFirstTurret: 0,
          takedowns: 22,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 6,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.33371562848747055,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 2,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 0,
          turretTakedowns: 3,
          turretsTakenWithRiftHerald: 5,
          twentyMinionsIn3SecondsCount: 3,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0.33998286724090576,
          visionScorePerMinute: 0.9330555846627261,
          wardTakedowns: 5,
          wardTakedownsBefore20M: 2,
          wardsGuarded: 0,
        } as any,
        champExperience: 19309,
        champLevel: 18,
        championId: 76,
        championName: "Nidalee",
        championTransform: 0,
        commandPings: 3,
        consumablesPurchased: 1,
        damageDealtToBuildings: 3407,
        damageDealtToObjectives: 36124,
        damageDealtToTurrets: 3407,
        damageSelfMitigated: 28785,
        dangerPings: 0,
        deaths: 5,
        detectorWardsPlaced: 1,
        doubleKills: 1,
        dragonKills: 0,
        eligibleForProgression: true,
        enemyMissingPings: 9,
        enemyVisionPings: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 0,
        goldEarned: 17645,
        goldSpent: 17575,
        holdPings: 0,
        individualPosition: "JUNGLE",
        inhibitorKills: 0,
        inhibitorTakedowns: 1,
        inhibitorsLost: 2,
        item0: 3089,
        item1: 3020,
        item2: 4645,
        item3: 3157,
        item4: 4636,
        item5: 3135,
        item6: 3364,
        itemsPurchased: 15,
        killingSprees: 1,
        kills: 10,
        lane: "JUNGLE",
        largestCriticalStrike: 0,
        largestKillingSpree: 8,
        largestMultiKill: 2,
        longestTimeSpentLiving: 804,
        magicDamageDealt: 265215,
        magicDamageDealtToChampions: 31043,
        magicDamageTaken: 10532,
        needVisionPings: 0,
        neutralMinionsKilled: 194,
        nexusKills: 0,
        nexusLost: 1,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 25,
        participantId: 7,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5002,
            flex: 5008,
            offense: 5005,
          },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                {
                  perk: 8128,
                  var1: 2249,
                  var2: 23,
                  var3: 0,
                },
                {
                  perk: 8143,
                  var1: 703,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8138,
                  var1: 30,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8135,
                  var1: 550,
                  var2: 5,
                  var3: 0,
                },
              ],
              style: 8100,
            },
            {
              description: "subStyle",
              selections: [
                {
                  perk: 8210,
                  var1: 10,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8232,
                  var1: 4,
                  var2: 30,
                  var3: 0,
                },
              ],
              style: 8200,
            },
          ],
        },
        physicalDamageDealt: 25166,
        physicalDamageDealtToChampions: 1289,
        physicalDamageTaken: 29657,
        profileIcon: 4050,
        pushPings: 3,
        puuid:
          "flqt87r0gFt0jkLEI9dlv2Srtto3gTJRkFPXWNYtbVDjbfJFyp2MtH6HoQdIPdyIO9Adu5hzf_DXEg",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "NONE",
        sightWardsBoughtInGame: 0,
        spell1Casts: 423,
        spell2Casts: 261,
        spell3Casts: 204,
        spell4Casts: 318,
        summoner1Casts: 4,
        summoner1Id: 4,
        summoner2Casts: 17,
        summoner2Id: 11,
        summonerId: "qc_mT0IjlhbvTiFx06k5U7a6x0FJoulX0Rh20IYQfHIjAu0",
        summonerLevel: 353,
        summonerName: "OIIOII",
        teamEarlySurrendered: false,
        teamId: 200,
        teamPosition: "JUNGLE",
        timeCCingOthers: 12,
        timePlayed: 2226,
        totalDamageDealt: 349959,
        totalDamageDealtToChampions: 35400,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 43464,
        totalHeal: 14393,
        totalHealsOnTeammates: 6605,
        totalMinionsKilled: 70,
        totalTimeCCDealt: 233,
        totalTimeSpentDead: 158,
        totalUnitsHealed: 4,
        tripleKills: 0,
        trueDamageDealt: 59577,
        trueDamageDealtToChampions: 3067,
        trueDamageTaken: 3274,
        turretKills: 3,
        turretTakedowns: 3,
        turretsLost: 9,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 34,
        visionWardsBoughtInGame: 1,
        wardsKilled: 5,
        wardsPlaced: 3,
        win: false,
      },
      {
        allInPings: 2,
        assistMePings: 0,
        assists: 11,
        baitPings: 1,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 0,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 403,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 22.500000059604645,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 0,
          buffsStolen: 0,
          completeSupportQuestInTime: 0,
          controlWardTimeCoverageInRiverOrEnemyHalf: 0.14503150764063885,
          controlWardsPlaced: 2,
          damagePerMinute: 704.0143390302275,
          damageTakenOnTeamPercentage: 0.16748057793314225,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 3,
          dodgeSkillShotsSmallWindow: 0,
          doubleAces: 0,
          dragonTakedowns: 0,
          earliestBaron: 1600.827670495282,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 12,
          enemyJungleMonsterKills: 2,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          firstTurretKilledTime: 957.7183454968596,
          flawlessAces: 0,
          fullTeamTakedown: 0,
          gameLength: 2226.724221852379,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 443.96554293670357,
          hadOpenNexus: 0,
          immobilizeAndKillWithAlly: 5,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 6.333333333333333,
          killAfterHiddenWithAlly: 2,
          killParticipation: 0.5428571428571428,
          killedChampTookFullTeamDamageSurvived: 0,
          killingSprees: 2,
          killsNearEnemyTurret: 2,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 0,
          killsWithHelpFromEpicMonster: 0,
          knockEnemyIntoTeamAndKill: 0,
          landSkillShotsEarlyGame: 0,
          laneMinionsFirst10Minutes: 82,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 32,
          maxKillDeficit: 0,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 1,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6653,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 2,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          pickKillWithAlly: 15,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 0,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 0,
          skillshotsDodged: 8,
          skillshotsHit: 11,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 5,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 2,
          takedownOnFirstTurret: 0,
          takedowns: 19,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 4,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.2462982882074873,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 2,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 0,
          turretTakedowns: 2,
          turretsTakenWithRiftHerald: 5,
          twentyMinionsIn3SecondsCount: 12,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0.029227137565612793,
          visionScorePerMinute: 0.6675271220177499,
          wardTakedowns: 5,
          wardTakedownsBefore20M: 1,
          wardsGuarded: 0,
        } as any,
        champExperience: 19731,
        champLevel: 18,
        championId: 105,
        championName: "Fizz",
        championTransform: 0,
        commandPings: 6,
        consumablesPurchased: 3,
        damageDealtToBuildings: 2531,
        damageDealtToObjectives: 9091,
        damageDealtToTurrets: 2531,
        damageSelfMitigated: 23486,
        dangerPings: 0,
        deaths: 3,
        detectorWardsPlaced: 2,
        doubleKills: 1,
        dragonKills: 0,
        eligibleForProgression: true,
        enemyMissingPings: 1,
        enemyVisionPings: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 0,
        goldEarned: 16476,
        goldSpent: 16300,
        holdPings: 1,
        individualPosition: "MIDDLE",
        inhibitorKills: 1,
        inhibitorTakedowns: 1,
        inhibitorsLost: 2,
        item0: 3135,
        item1: 3157,
        item2: 3041,
        item3: 3089,
        item4: 3158,
        item5: 6653,
        item6: 3364,
        itemsPurchased: 20,
        killingSprees: 2,
        kills: 8,
        lane: "MIDDLE",
        largestCriticalStrike: 0,
        largestKillingSpree: 4,
        largestMultiKill: 2,
        longestTimeSpentLiving: 1103,
        magicDamageDealt: 184937,
        magicDamageDealtToChampions: 21853,
        magicDamageTaken: 8364,
        needVisionPings: 0,
        neutralMinionsKilled: 26,
        nexusKills: 0,
        nexusLost: 1,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 9,
        participantId: 8,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5003,
            flex: 5008,
            offense: 5005,
          },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                {
                  perk: 8112,
                  var1: 2194,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8143,
                  var1: 868,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8138,
                  var1: 30,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8135,
                  var1: 550,
                  var2: 5,
                  var3: 0,
                },
              ],
              style: 8100,
            },
            {
              description: "subStyle",
              selections: [
                {
                  perk: 8345,
                  var1: 3,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8347,
                  var1: 0,
                  var2: 0,
                  var3: 0,
                },
              ],
              style: 8300,
            },
          ],
        },
        physicalDamageDealt: 39234,
        physicalDamageDealtToChampions: 4202,
        physicalDamageTaken: 20942,
        profileIcon: 4657,
        pushPings: 2,
        puuid:
          "l1tRZP9q6onsrK_tQGM5hQut5JzVlKxzkKQv66__F9UIVjvBgsVsi3eva6SCHmcIgMfLdg1WqteBYA",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "SOLO",
        sightWardsBoughtInGame: 0,
        spell1Casts: 84,
        spell2Casts: 140,
        spell3Casts: 161,
        spell4Casts: 18,
        summoner1Casts: 5,
        summoner1Id: 12,
        summoner2Casts: 6,
        summoner2Id: 4,
        summonerId: "Q3v_Zi2C2swaVKhnEUsv_uu_KblnjLmJw_did7Gy1moJSsQ",
        summonerLevel: 431,
        summonerName: "ShowLaker",
        teamEarlySurrendered: false,
        teamId: 200,
        teamPosition: "MIDDLE",
        timeCCingOthers: 17,
        timePlayed: 2226,
        totalDamageDealt: 237059,
        totalDamageDealtToChampions: 26127,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 32083,
        totalHeal: 4169,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 260,
        totalTimeCCDealt: 230,
        totalTimeSpentDead: 68,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 12887,
        trueDamageDealtToChampions: 72,
        trueDamageTaken: 2776,
        turretKills: 0,
        turretTakedowns: 2,
        turretsLost: 9,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 24,
        visionWardsBoughtInGame: 2,
        wardsKilled: 5,
        wardsPlaced: 7,
        win: false,
      },
      {
        allInPings: 0,
        assistMePings: 0,
        assists: 9,
        baitPings: 3,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 0,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 145,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 7,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 150,
          buffsStolen: 1,
          completeSupportQuestInTime: 0,
          controlWardTimeCoverageInRiverOrEnemyHalf: 0.3972880728958206,
          controlWardsPlaced: 1,
          damagePerMinute: 376.70545455262925,
          damageTakenOnTeamPercentage: 0.13805359318789182,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 9,
          dodgeSkillShotsSmallWindow: 0,
          doubleAces: 0,
          dragonTakedowns: 0,
          earliestBaron: 1600.827670495282,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 319.144287109375,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 10,
          enemyJungleMonsterKills: 8,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          firstTurretKilledTime: 957.7183454968596,
          flawlessAces: 0,
          fullTeamTakedown: 0,
          gameLength: 2226.724221852379,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 386.10432451634654,
          hadOpenNexus: 0,
          immobilizeAndKillWithAlly: 4,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 1.5555555555555556,
          killAfterHiddenWithAlly: 1,
          killParticipation: 0.4,
          killedChampTookFullTeamDamageSurvived: 0,
          killsNearEnemyTurret: 1,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 1,
          killsWithHelpFromEpicMonster: 0,
          knockEnemyIntoTeamAndKill: 0,
          landSkillShotsEarlyGame: 0,
          laneMinionsFirst10Minutes: 46,
          laningPhaseGoldExpAdvantage: 1,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 18.599999994039536,
          maxKillDeficit: 0,
          maxLevelLeadLaneOpponent: 3,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6671,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 1,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          pickKillWithAlly: 12,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 0,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 1,
          skillshotsDodged: 7,
          skillshotsHit: 6,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 1,
          stealthWardsPlaced: 9,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 0,
          takedownOnFirstTurret: 1,
          takedowns: 14,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 8,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.1317897995409328,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 2,
          threeWardsOneSweeperCount: 0,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 2,
          turretTakedowns: 3,
          turretsTakenWithRiftHerald: 5,
          twentyMinionsIn3SecondsCount: 7,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0.6403400897979736,
          visionScorePerMinute: 0.7904671542776611,
          wardTakedowns: 2,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 0,
        } as any,
        champExperience: 13619,
        champLevel: 15,
        championId: 202,
        championName: "Jhin",
        championTransform: 0,
        commandPings: 1,
        consumablesPurchased: 2,
        damageDealtToBuildings: 5531,
        damageDealtToObjectives: 7792,
        damageDealtToTurrets: 5531,
        damageSelfMitigated: 13695,
        dangerPings: 0,
        deaths: 9,
        detectorWardsPlaced: 1,
        doubleKills: 0,
        dragonKills: 0,
        eligibleForProgression: true,
        enemyMissingPings: 5,
        enemyVisionPings: 0,
        firstBloodAssist: true,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 0,
        goldEarned: 14329,
        goldSpent: 13850,
        holdPings: 0,
        individualPosition: "BOTTOM",
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 2,
        item0: 6671,
        item1: 3009,
        item2: 3094,
        item3: 6676,
        item4: 3033,
        item5: 1037,
        item6: 3340,
        itemsPurchased: 23,
        killingSprees: 0,
        kills: 5,
        lane: "BOTTOM",
        largestCriticalStrike: 1286,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        longestTimeSpentLiving: 392,
        magicDamageDealt: 5037,
        magicDamageDealtToChampions: 3320,
        magicDamageTaken: 5217,
        needVisionPings: 0,
        neutralMinionsKilled: 19,
        nexusKills: 0,
        nexusLost: 1,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 5,
        participantId: 9,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5002,
            flex: 5008,
            offense: 5008,
          },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                {
                  perk: 8021,
                  var1: 1999,
                  var2: 1682,
                  var3: 0,
                },
                {
                  perk: 8009,
                  var1: 973,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 9103,
                  var1: 25,
                  var2: 30,
                  var3: 0,
                },
                {
                  perk: 8017,
                  var1: 124,
                  var2: 0,
                  var3: 0,
                },
              ],
              style: 8000,
            },
            {
              description: "subStyle",
              selections: [
                {
                  perk: 8233,
                  var1: 23,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8236,
                  var1: 28,
                  var2: 0,
                  var3: 0,
                },
              ],
              style: 8200,
            },
          ],
        },
        physicalDamageDealt: 137728,
        physicalDamageDealtToChampions: 10317,
        physicalDamageTaken: 18623,
        profileIcon: 666,
        pushPings: 2,
        puuid:
          "KemdVt3dt9OdUcAJP8JFKS85mEmn_QLuF0WhvETnGdFGHfdWnCk92CiXL5umHw53-uQkNuKsTGKgXA",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "CARRY",
        sightWardsBoughtInGame: 0,
        spell1Casts: 73,
        spell2Casts: 23,
        spell3Casts: 37,
        spell4Casts: 12,
        summoner1Casts: 5,
        summoner1Id: 4,
        summoner2Casts: 5,
        summoner2Id: 7,
        summonerId: "AnCoFklfpftjTzCQ-bNoPnzWK0xfMZAf1wImMKENDvBbcto",
        summonerLevel: 228,
        summonerName: "pyndulak",
        teamEarlySurrendered: false,
        teamId: 200,
        teamPosition: "BOTTOM",
        timeCCingOthers: 19,
        timePlayed: 2226,
        totalDamageDealt: 143462,
        totalDamageDealtToChampions: 13980,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 26446,
        totalHeal: 3687,
        totalHealsOnTeammates: 319,
        totalMinionsKilled: 179,
        totalTimeCCDealt: 87,
        totalTimeSpentDead: 275,
        totalUnitsHealed: 2,
        tripleKills: 0,
        trueDamageDealt: 696,
        trueDamageDealtToChampions: 342,
        trueDamageTaken: 2605,
        turretKills: 3,
        turretTakedowns: 3,
        turretsLost: 9,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 29,
        visionWardsBoughtInGame: 1,
        wardsKilled: 2,
        wardsPlaced: 10,
        win: false,
      },
      {
        allInPings: 0,
        assistMePings: 7,
        assists: 3,
        baitPings: 1,
        baronKills: 0,
        basicPings: 0,
        bountyLevel: 0,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 181,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 4,
          baronTakedowns: 1,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 0,
          buffsStolen: 0,
          completeSupportQuestInTime: 0,
          controlWardTimeCoverageInRiverOrEnemyHalf: 0.051820892346111216,
          controlWardsPlaced: 1,
          damagePerMinute: 310.70209067839215,
          damageTakenOnTeamPercentage: 0.1461247156534047,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 11,
          dodgeSkillShotsSmallWindow: 1,
          doubleAces: 0,
          dragonTakedowns: 0,
          earliestBaron: 1600.827670495282,
          earlyLaningPhaseGoldExpAdvantage: 1,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 29,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          epicMonsterStolenWithoutSmite: 0,
          firstTurretKilledTime: 957.7183454968596,
          flawlessAces: 0,
          fullTeamTakedown: 0,
          gameLength: 2226.724221852379,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 309.2968506398898,
          hadOpenNexus: 0,
          highestWardKills: 1,
          immobilizeAndKillWithAlly: 8,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kTurretsDestroyedBeforePlatesFall: 0,
          kda: 1.1818181818181819,
          killAfterHiddenWithAlly: 1,
          killParticipation: 0.37142857142857144,
          killedChampTookFullTeamDamageSurvived: 0,
          killingSprees: 1,
          killsNearEnemyTurret: 3,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 1,
          killsWithHelpFromEpicMonster: 0,
          knockEnemyIntoTeamAndKill: 5,
          landSkillShotsEarlyGame: 7,
          laneMinionsFirst10Minutes: 27,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 55,
          maxKillDeficit: 0,
          maxLevelLeadLaneOpponent: 2,
          moreEnemyJungleThanOpponent: 0,
          multiKillOneSpell: 0,
          multiTurretRiftHeraldCount: 0,
          multikills: 3,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6691,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 2,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          pickKillWithAlly: 12,
          playedChampSelectPosition: 1,
          poroExplosions: 0,
          quickCleanse: 0,
          quickFirstTurret: 0,
          quickSoloKills: 0,
          riftHeraldTakedowns: 0,
          saveAllyFromDeath: 0,
          scuttleCrabKills: 0,
          skillshotsDodged: 8,
          skillshotsHit: 28,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 22,
          survivedSingleDigitHpCount: 0,
          survivedThreeImmobilizesInFight: 0,
          takedownOnFirstTurret: 0,
          takedowns: 13,
          takedownsAfterGainingLevelAdvantage: 1,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirstXMinutes: 8,
          takedownsInAlcove: 1,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 1,
          teamDamagePercentage: 0.1086986284711025,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 2,
          threeWardsOneSweeperCount: 1,
          tookLargeDamageSurvived: 0,
          turretPlatesTaken: 2,
          turretTakedowns: 1,
          turretsTakenWithRiftHerald: 5,
          twentyMinionsIn3SecondsCount: 3,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: -0.09589940309524536,
          visionScorePerMinute: 2.089357495399656,
          wardTakedowns: 19,
          wardTakedownsBefore20M: 6,
          wardsGuarded: 1,
        } as any,
        champExperience: 10354,
        champLevel: 13,
        championId: 555,
        championName: "Pyke",
        championTransform: 0,
        commandPings: 1,
        consumablesPurchased: 3,
        damageDealtToBuildings: 1220,
        damageDealtToObjectives: 2855,
        damageDealtToTurrets: 1220,
        damageSelfMitigated: 14513,
        dangerPings: 0,
        deaths: 11,
        detectorWardsPlaced: 1,
        doubleKills: 3,
        dragonKills: 0,
        eligibleForProgression: true,
        enemyMissingPings: 1,
        enemyVisionPings: 0,
        firstBloodAssist: false,
        firstBloodKill: true,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        getBackPings: 5,
        goldEarned: 11478,
        goldSpent: 11075,
        holdPings: 1,
        individualPosition: "UTILITY",
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 2,
        item0: 3142,
        item1: 3857,
        item2: 6691,
        item3: 3117,
        item4: 3179,
        item5: 3134,
        item6: 3364,
        itemsPurchased: 26,
        killingSprees: 1,
        kills: 10,
        lane: "BOTTOM",
        largestCriticalStrike: 0,
        largestKillingSpree: 7,
        largestMultiKill: 2,
        longestTimeSpentLiving: 749,
        magicDamageDealt: 0,
        magicDamageDealtToChampions: 0,
        magicDamageTaken: 7010,
        needVisionPings: 0,
        neutralMinionsKilled: 4,
        nexusKills: 0,
        nexusLost: 1,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        onMyWayPings: 19,
        participantId: 10,
        pentaKills: 0,
        perks: {
          statPerks: {
            defense: 5001,
            flex: 5008,
            offense: 5008,
          },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                {
                  perk: 9923,
                  var1: 23,
                  var2: 63,
                  var3: 0,
                },
                {
                  perk: 8126,
                  var1: 363,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8138,
                  var1: 18,
                  var2: 0,
                  var3: 0,
                },
                {
                  perk: 8106,
                  var1: 4,
                  var2: 0,
                  var3: 0,
                },
              ],
              style: 8100,
            },
            {
              description: "subStyle",
              selections: [
                {
                  perk: 9111,
                  var1: 532,
                  var2: 260,
                  var3: 0,
                },
                {
                  perk: 8014,
                  var1: 178,
                  var2: 0,
                  var3: 0,
                },
              ],
              style: 8000,
            },
          ],
        },
        physicalDamageDealt: 32944,
        physicalDamageDealtToChampions: 9403,
        physicalDamageTaken: 19466,
        profileIcon: 597,
        pushPings: 0,
        puuid:
          "eQHq45lNyjyGpjtqbRWAIB-39ftKYWvEaEqq-cOOSlM-sznts3_qzKdIxLAsWiMyKeErrMTskbUOLg",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "SUPPORT",
        sightWardsBoughtInGame: 0,
        spell1Casts: 70,
        spell2Casts: 60,
        spell3Casts: 43,
        spell4Casts: 8,
        summoner1Casts: 4,
        summoner1Id: 4,
        summoner2Casts: 6,
        summoner2Id: 14,
        summonerId: "sKXJ9Vu5Y-8Flm5ioXkD_Vd110c8p8LZMQADr_c81-dvFPc",
        summonerLevel: 285,
        summonerName: "Filipínek",
        teamEarlySurrendered: false,
        teamId: 200,
        teamPosition: "UTILITY",
        timeCCingOthers: 26,
        timePlayed: 2226,
        totalDamageDealt: 41967,
        totalDamageDealtToChampions: 11530,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 27992,
        totalHeal: 3088,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 62,
        totalTimeCCDealt: 102,
        totalTimeSpentDead: 337,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 9023,
        trueDamageDealtToChampions: 2127,
        trueDamageTaken: 1516,
        turretKills: 0,
        turretTakedowns: 1,
        turretsLost: 9,
        unrealKills: 0,
        visionClearedPings: 0,
        visionScore: 77,
        visionWardsBoughtInGame: 1,
        wardsKilled: 19,
        wardsPlaced: 23,
        win: false,
      },
    ],
    platformId: "EUN1",
    queueId: 440,
    teams: [
      {
        bans: [
          {
            championId: 517,
            pickTurn: 1,
          },
          {
            championId: 98,
            pickTurn: 2,
          },
          {
            championId: 145,
            pickTurn: 3,
          },
          {
            championId: 51,
            pickTurn: 4,
          },
          {
            championId: 120,
            pickTurn: 5,
          },
        ],
        objectives: {
          baron: {
            first: false,
            kills: 1,
          },
          champion: {
            first: false,
            kills: 34,
          },
          dragon: {
            first: true,
            kills: 5,
          },
          inhibitor: {
            first: false,
            kills: 2,
          },
          riftHerald: {
            first: true,
            kills: 1,
          },
          tower: {
            first: false,
            kills: 9,
          },
        },
        teamId: 100,
        win: true,
      },
      {
        bans: [
          {
            championId: 412,
            pickTurn: 6,
          },
          {
            championId: 360,
            pickTurn: 7,
          },
          {
            championId: 23,
            pickTurn: 8,
          },
          {
            championId: 350,
            pickTurn: 9,
          },
          {
            championId: 157,
            pickTurn: 10,
          },
        ],
        objectives: {
          baron: {
            first: true,
            kills: 1,
          },
          champion: {
            first: true,
            kills: 35,
          },
          dragon: {
            first: false,
            kills: 0,
          },
          inhibitor: {
            first: true,
            kills: 2,
          },
          riftHerald: {
            first: false,
            kills: 1,
          },
          tower: {
            first: true,
            kills: 8,
          },
        },
        teamId: 200,
        win: false,
      },
    ],
    tournamentCode: "",
  },
};
