export const queues = {
  0: {
    name: "Custom",
    map: "Custom games",
    description: null,
    notes: null,
  },
  2: {
    name: "Normal",
    map: "Summoner's Rift",
    description: "5v5 Blind Pick games",
    notes: "Deprecated in patch 7.19 in favor of queueId 430",
  },
  4: {
    name: "Ranked Solo",
    map: "Summoner's Rift",
    description: "5v5 Ranked Solo games",
    notes: "Deprecated in favor of queueId 420",
  },
  6: {
    name: "Ranked Premade",
    map: "Summoner's Rift",
    description: "5v5 Ranked Premade games",
    notes: "Game mode deprecated",
  },
  7: {
    name: "Co-op vs AI",
    map: "Summoner's Rift",
    description: "Co-op vs AI games",
    notes: "Deprecated in favor of queueId 32 and 33",
  },
  8: {
    name: "Normal 3v3",
    map: "Twisted Treeline",
    description: "3v3 Normal games",
    notes: "Deprecated in patch 7.19 in favor of queueId 460",
  },
  9: {
    name: "Ranked 3v3",
    map: "Twisted Treeline",
    description: "3v3 Ranked Flex games",
    notes: "Deprecated in patch 7.19 in favor of queueId 470",
  },
  14: {
    name: "Normal",
    map: "Summoner's Rift",
    description: "5v5 Draft Pick games",
    notes: "Deprecated in favor of queueId 400",
  },
  16: {
    name: "Dominion",
    map: "Crystal Scar",
    description: "5v5 Dominion Blind Pick games",
    notes: "Game mode deprecated",
  },
  17: {
    name: "Dominion",
    map: "Crystal Scar",
    description: "5v5 Dominion Draft Pick games",
    notes: "Game mode deprecated",
  },
  25: {
    name: "Dominion",
    map: "Crystal Scar",
    description: "Dominion Co-op vs AI games",
    notes: "Game mode deprecated",
  },
  31: {
    name: "Co-op vs AI",
    map: "Summoner's Rift",
    description: "Co-op vs AI Intro Bot games",
    notes: "Deprecated in patch 7.19 in favor of queueId 830",
  },
  32: {
    name: "Co-op vs AI",
    map: "Summoner's Rift",
    description: "Co-op vs AI Beginner Bot games",
    notes: "Deprecated in patch 7.19 in favor of queueId 840",
  },
  33: {
    name: "Co-op vs AI",
    map: "Summoner's Rift",
    description: "Co-op vs AI Intermediate Bot games",
    notes: "Deprecated in patch 7.19 in favor of queueId 850",
  },
  41: {
    name: "3v3 Ranked",
    map: "Twisted Treeline",
    description: "3v3 Ranked Team games",
    notes: "Game mode deprecated",
  },
  72: {
    name: "1v1",
    map: "Howling Abyss",
    description: "1v1 Snowdown Showdown games",
    notes: null,
  },
  73: {
    name: "2v2",
    map: "Howling Abyss",
    description: "2v2 Snowdown Showdown games",
    notes: null,
  },
  75: {
    name: "HEXAKILL",
    map: "Summoner's Rift",
    description: "6v6 Hexakill games",
    notes: null,
  },
  76: {
    name: "URF",
    map: "Summoner's Rift",
    description: "Ultra Rapid Fire games",
    notes: null,
  },
  78: {
    name: "One for All",
    map: "Howling Abyss",
    description: "One For All: Mirror Mode games",
    notes: null,
  },
  83: {
    name: "URF",
    map: "Summoner's Rift",
    description: "Co-op vs AI Ultra Rapid Fire games",
    notes: null,
  },
  91: {
    name: "DOOM BOTS",
    map: "Summoner's Rift",
    description: "Doom Bots Rank 1 games",
    notes: "Deprecated in patch 7.19 in favor of queueId 950",
  },
  92: {
    name: "DOOM BOTS",
    map: "Summoner's Rift",
    description: "Doom Bots Rank 1 games",
    notes: "Deprecated in patch 7.19 in favor of queueId 950",
  },
  93: {
    name: "DOOM BOTS",
    map: "Summoner's Rift",
    description: "Doom Bots Rank 1 games",
    notes: "Deprecated in patch 7.19 in favor of queueId 950",
  },
  96: {
    name: "Ascension",
    map: "Crystal Scar",
    description: "Ascension games",
    notes: "Deprecated in patch 7.19 in favor of queueId 910",
  },
  98: {
    name: "HEXAKILL",
    map: "Twisted Treeline",
    description: "6v6 Hexakill games",
    notes: null,
  },
  100: {
    name: "ARAM",
    map: "Butcher's Bridge",
    description: "5v5 ARAM games",
    notes: null,
  },
  300: {
    name: "ARAM",
    map: "Howling Abyss",
    description: "Legend of the Poro King games",
    notes: "Deprecated in patch 7.19 in favor of queueId 920",
  },
  310: {
    name: "NEMESIS",
    map: "Summoner's Rift",
    description: "Nemesis games",
    notes: null,
  },
  313: {
    name: "BMB",
    map: "Summoner's Rift",
    description: "Black Market Brawlers games",
    notes: null,
  },
  315: {
    name: "NEXUS SIEGE",
    map: "Summoner's Rift",
    description: "Nexus Siege games",
    notes: "Deprecated in patch 7.19 in favor of queueId 940",
  },
  317: {
    name: "Dominion",
    map: "Crystal Scar",
    description: "Definitely Not Dominion games",
    notes: null,
  },
  318: {
    name: "URF",
    map: "Summoner's Rift",
    description: "ARURF games",
    notes: "Deprecated in patch 7.19 in favor of queueId 900",
  },
  325: {
    name: "ARAM",
    map: "Summoner's Rift",
    description: "All Random games",
    notes: null,
  },
  400: {
    name: "Normal",
    map: "Summoner's Rift",
    description: "5v5 Draft Pick games",
    notes: null,
  },
  410: {
    name: "Ranked",
    map: "Summoner's Rift",
    description: "5v5 Ranked Dynamic games",
    notes: "Game mode deprecated in patch 6.22",
  },
  420: {
    name: "Ranked Solo",
    map: "Summoner's Rift",
    description: "5v5 Ranked Solo games",
    notes: null,
  },
  430: {
    name: "Normal",
    map: "Summoner's Rift",
    description: "5v5 Blind Pick games",
    notes: null,
  },
  440: {
    name: "Ranked Flex",
    map: "Summoner's Rift",
    description: "5v5 Ranked Flex games",
    notes: null,
  },
  450: {
    name: "ARAM",
    map: "Howling Abyss",
    description: "5v5 ARAM games",
    notes: null,
  },
  460: {
    name: "Normal 3v3",
    map: "Twisted Treeline",
    description: "3v3 Blind Pick games",
    notes: "Deprecated in patch 9.23",
  },
  470: {
    name: "Ranked 3v3",
    map: "Twisted Treeline",
    description: "3v3 Ranked Flex games",
    notes: "Deprecated in patch 9.23",
  },
  600: {
    name: "Blood Hunt",
    map: "Summoner's Rift",
    description: "Blood Hunt Assassin games",
    notes: null,
  },
  610: {
    name: "Dark Star",
    map: "Cosmic Ruins",
    description: "Dark Star: Singularity games",
    notes: null,
  },
  700: {
    name: "Clash",
    map: "Summoner's Rift",
    description: "Clash games",
    notes: null,
  },
  800: {
    name: "Co-op vs. AI",
    map: "Twisted Treeline",
    description: "Co-op vs. AI Intermediate Bot games",
    notes: "Deprecated in patch 9.23",
  },
  810: {
    name: "Co-op vs. AI",
    map: "Twisted Treeline",
    description: "Co-op vs. AI Intro Bot games",
    notes: "Deprecated in patch 9.23",
  },
  820: {
    name: "Co-op vs. AI",

    map: "Twisted Treeline",
    description: "Co-op vs. AI Beginner Bot games",
    notes: null,
  },
  830: {
    name: "Co-op vs. AI",
    map: "Summoner's Rift",
    description: "Co-op vs. AI Intro Bot games",
    notes: null,
  },
  840: {
    name: "Co-op vs. AI",
    map: "Summoner's Rift",
    description: "Co-op vs. AI Beginner Bot games",
    notes: null,
  },
  850: {
    name: "Co-op vs. AI",
    map: "Summoner's Rift",
    description: "Co-op vs. AI Intermediate Bot games",
    notes: null,
  },
  900: {
    name: "URF",
    map: "Summoner's Rift",
    description: "ARURF games",
    notes: null,
  },
  910: {
    name: "Ascension",
    map: "Crystal Scar",
    description: "Ascension games",
    notes: null,
  },
  920: {
    name: "ARAM",
    map: "Howling Abyss",
    description: "Legend of the Poro King games",
    notes: null,
  },
  940: {
    name: "Nexus Siege",
    map: "Summoner's Rift",
    description: "Nexus Siege games",
    notes: null,
  },
  950: {
    name: "Doom Bots",
    map: "Summoner's Rift",
    description: "Doom Bots Voting games",
    notes: null,
  },
  960: {
    name: "Doom Bots",
    map: "Summoner's Rift",
    description: "Doom Bots Standard games",
    notes: null,
  },
  980: {
    name: "Star Guardian Invasion",
    map: "Valoran City Park",
    description: "Star Guardian Invasion: Normal games",
    notes: null,
  },
  990: {
    name: "Star Guardian Invasion",
    map: "Valoran City Park",
    description: "Star Guardian Invasion: Onslaught games",
    notes: null,
  },
  1000: {
    name: "PROJECT",
    map: "Overcharge",
    description: "PROJECT: Hunters games",
    notes: null,
  },
  1010: {
    name: "URF",
    map: "Summoner's Rift",
    description: "Snow ARURF games",
    notes: null,
  },
  1020: {
    name: "One for All",
    map: "Summoner's Rift",
    description: "One for All games",
    notes: null,
  },
  1030: {
    name: "Odyssey Extraction",
    map: "Crash Site",
    description: "Odyssey Extraction: Intro games",
    notes: null,
  },
  1040: {
    name: "Odyssey Extraction",
    map: "Crash Site",
    description: "Odyssey Extraction: Intro games",
    notes: null,
  },
  1050: {
    name: "Odyssey Extraction",
    map: "Crash Site",
    description: "Odyssey Extraction: Intro games",
    notes: null,
  },
  1060: {
    name: "Odyssey Extraction",
    map: "Crash Site",
    description: "Odyssey Extraction: Intro games",
    notes: null,
  },
  1070: {
    name: "Odyssey Extraction",
    map: "Crash Site",
    description: "Odyssey Extraction: Intro games",
    notes: null,
  },
  1090: {
    name: "TFT",
    map: "Convergence",
    description: "Teamfight Tactics games",
    notes: null,
  },
  1100: {
    name: "Ranked TFT",
    map: "Convergence",
    description: "RANKED Teamfight Tactics games",
    notes: null,
  },
  1111: {
    name: "TFT",
    map: "Convergence",
    description: "Teamfight Tactics games",
    notes: null,
  },
  1700: {
    name: "SOULFIGHTER",
    map: "CHERRY",
    description: "Soul fight to death",
    notes: "new game mode",
  },
};

export type queueModes = keyof typeof queues;

export type queueMode = typeof queues[queueModes];
